# Generated by Django 5.2.8 on 2026-05-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(help_text='Client/Institution ID', max_length=100)),
                ('date', models.DateField(help_text='Date of the event')),
                ('event_type', models.CharField(choices=[('H', 'Holiday'), ('L', 'Leave'), ('E', 'Event')], default='H', help_text='Type of calendar event', max_length=1)),
                ('title', models.CharField(help_text='Title/Name of the event', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this event is active')),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['date'],
                'unique_together': {('institution_id', 'date')},
            },
        ),
    ]
