# Generated by Django 5.0.14 on 2026-06-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_categories', '0002_rename_client_id_jobcategory_institution_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
