# Generated by Django 5.2.8 on 2026-04-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_administrators', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administratorprofile',
            old_name='client_id',
            new_name='institution_id',
        ),
    ]
