# Generated by Django 5.0.14 on 2026-06-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_administrators', '0003_schoolinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='id_card_form_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
