# Generated by Django 5.2.8 on 2026-04-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('admno', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=200)),
                ('mothername', models.CharField(max_length=200)),
                ('imageurl', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=200)),
                ('remark', models.TextField(blank=True, null=True)),
                ('refno', models.CharField(max_length=100)),
            ],
        ),
    ]
