# Generated by Django 5.0.14 on 2026-06-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0002_rename_client_id_studentdata_institution_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='fathername',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='mothername',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='refno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
