# Generated by Django 5.0.14 on 2026-06-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0003_alter_studentdata_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='div',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
