# Generated by Django 5.2.8 on 2026-05-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_manage', '0003_alter_teacher_options_teacher_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
