# Generated by Django 5.0.14 on 2026-06-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_manage', '0004_teacher_assigned_class_teacher_assigned_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='additional_class_assignments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
