# Generated by Django 5.2.8 on 2026-04-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeePending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('admno', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('particulars', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refno', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
